### ISSUE TITLE
Question regarding the solution for Question 1 of Section 1

### ISSUE THREAD

**Issue by nhattan417** [Datseris/Zero2Hero-JuliaWorkshop#11]
Hi, I have been going through the tutorial and want to check for the solution. I believe line number 5 in solution 1:
https://github.com/Datseris/Zero2Hero-JuliaWorkshop/blob/3929cb090214ced54bd73f5eee0ecb806c8c667b/solutions_1.jl#L5
Instead, should be checking condition that includes $y$:
```julia
    while abs(x - sqrt(y)) > ε
```
or
```julia
    while abs(xn - sqrt(y)) > ε
```
In fact, I think we only need either $x$ or $xn$ but not both? Correct me if I am wrong. Thank you!

**Comment by Datseris** [comment]
hi, `abs(x - xn) > ε` is also a correct thing to check. `x, xn` are current and previous steps of a sequence that approximates `sqrt(y)`. You can estimate convergence by estimating how close you are to `sqrt(y)`, like you suggested. But you can also estiamte convergence by how little `xn` has changed from its previous value `x`. 

The whole point of this function/algorithm is to find `sqrt(y)`. If you can just call `sqrt(y)` inside the function, the function itself becomes pointless :)

**Comment by nhattan417** [comment]
Ah yes, by Cauchy Criterion. I misread the instruction from the exercises that: "... takes some convergence tolerance `ε` to compare with the built-in `sqrt(y)`." Thank you the clarification.
