### ISSUE TITLE
Question regarding the solution for "Advanced whackadoodle iterator" of Section 2

### ISSUE THREAD

**Issue by nhattan417** [Datseris/Zero2Hero-JuliaWorkshop#12]
This is just a minor question: why are we excluding the last index element `i == w.n`?
https://github.com/Datseris/Zero2Hero-JuliaWorkshop/blob/3929cb090214ced54bd73f5eee0ecb806c8c667b/solutions_2.jl#L98-L109
Does the below means we want to make exactly "`n` loops" or we want to have "`n` elements" that can be printed? Are we expecting same behaviour as using for loop on a range `1:n` which includes both "start" and "end"?
https://github.com/Datseris/Zero2Hero-JuliaWorkshop/blob/3929cb090214ced54bd73f5eee0ecb806c8c667b/2-MultipleDispatch.ipynb#L2235
Thank you.

**Comment by Datseris** [comment]
yeah it should be `i == w.n+1`
